In [2]:
import os
import pandas as pd
import numpy as np

In [3]:
os.chdir(r'C:\Users\jaij2\OneDrive\바탕 화면\커뮤니티\데이터\NC')
bat_19 = pd.read_excel('2017_2021_NC_타자.xlsx')
bat_19

,연도,선수명,팀명,경기,타석,타수,안타,단타,2루타,3루타,...,볼넷,고4,HBP,삼진,희플,희타,병살,도루,도실,타율
0,2017,나성범,NC,125,561,498,173,105,42,2,...,48,10,12,116,3,3,8,17,7,0.347
1,2017,박민우,NC,106,452,388,141,109,25,4,...,46,0,11,51,4,7,8,11,1,0.363
2,2017,스크럭스,NC,115,518,437,131,72,24,0,...,65,2,12,134,4,4,8,4,0,0.3
3,2017,손시헌,NC,124,391,349,122,99,17,1,...,16,1,8,44,5,18,5,1,0,0.35
4,2017,권희동,NC,141,554,472,135,94,20,2,...,52,1,16,90,7,14,12,3,3,0.286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2021,최승민,NC,48,34,31,7,6,1,0,...,1,0,0,7,0,2,0,4,3,0.226
155,2021,정진기,NC,86,199,186,43,29,8,0,...,10,0,1,37,0,2,2,6,3,0.231
156,2021,김기환,NC,62,149,140,29,17,7,2,...,8,0,0,45,0,1,1,15,3,0.207
157,2021,박대온,NC,42,95,85,18,17,1,0,...,4,0,0,21,2,6,0,0,0,0.212
158,2021,이원재,NC,31,69,65,15,13,2,0,...,1,0,1,11,1,2,1,1,0,0.231

In [5]:
BB = bat_19['볼넷']
HIT = bat_19['안타']
HIT1 = bat_19['단타']
HIT2 = bat_19['2루타']
HIT3 = bat_19['3루타']
HR = bat_19['홈런']
PA = bat_19['타석']
AB = bat_19['타수']
RBI = bat_19['타점']
RUN = bat_19['득점']
HP = bat_19['HBP']
SB = bat_19['도루']
CS = bat_19['도실']
GD = bat_19['병살']
IB = bat_19['고4']
SH = bat_19['희타']
SF = bat_19['희플']
KK = bat_19['삼진']
# P_HIT_CN = bat_19['P_HIT_CN']
# P_AB_CN = bat_19['P_AB_CN']

### OPS

#### 출루율 (안타+볼넷+몸에 맞은 공) / (타수+볼넷+몸에 맞은 공+희생플라이)
(HIT+BB+HP)/(AB+BB+HP+SF)

In [6]:
OBP_list = []
for i in range(0, len(bat_19)) :
    up = HIT[i] + BB[i] + HP[i]
    down = AB[i] + BB[i] + HP[i] + SF[i]
    OBP = up/down
    OBP_list.append(OBP)

<ipython-input-6-099e36aed1fd>:5: RuntimeWarning: invalid value encountered in longlong_scalars
  OBP = up/down

In [7]:
bat_19['OBP'] = OBP_list
bat_19

,연도,선수명,팀명,경기,타석,타수,안타,단타,2루타,3루타,...,고4,HBP,삼진,희플,희타,병살,도루,도실,타율,OBP
0,2017,나성범,NC,125,561,498,173,105,42,2,...,10,12,116,3,3,8,17,7,0.347,0.415330
1,2017,박민우,NC,106,452,388,141,109,25,4,...,0,11,51,4,7,8,11,1,0.363,0.440980
2,2017,스크럭스,NC,115,518,437,131,72,24,0,...,2,12,134,4,4,8,4,0,0.3,0.401544
3,2017,손시헌,NC,124,391,349,122,99,17,1,...,1,8,44,5,18,5,1,0,0.35,0.386243
4,2017,권희동,NC,141,554,472,135,94,20,2,...,1,16,90,7,14,12,3,3,0.286,0.371115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2021,최승민,NC,48,34,31,7,6,1,0,...,0,0,7,0,2,0,4,3,0.226,0.250000
155,2021,정진기,NC,86,199,186,43,29,8,0,...,0,1,37,0,2,2,6,3,0.231,0.274112
156,2021,김기환,NC,62,149,140,29,17,7,2,...,0,0,45,0,1,1,15,3,0.207,0.250000
157,2021,박대온,NC,42,95,85,18,17,1,0,...,0,0,21,2,6,0,0,0,0.212,0.241758
158,2021,이원재,NC,31,69,65,15,13,2,0,...,0,1,11,1,2,1,1,0,0.231,0.250000

#### 장타율 (단타 수 + 2루타 수*2 + 3루타 수*3 + 홈런 수*4)/타수

In [8]:
SLG_list = []
for j in range(0, len(bat_19)) :
    hit1 = HIT1[j]
    hit2 = HIT2[j] * 2
    hit3 = HIT3[j] * 3
    hit4 = HR[j] * 4
    
    up = hit1 + hit2 + hit3 + hit4
    down = AB[j]
    
    SLG = up/down
    SLG_list.append(SLG)

<ipython-input-8-f6d4c008d58e>:11: RuntimeWarning: invalid value encountered in longlong_scalars
  SLG = up/down

In [9]:
bat_19['SLG'] = SLG_list
bat_19

,연도,선수명,팀명,경기,타석,타수,안타,단타,2루타,3루타,...,HBP,삼진,희플,희타,병살,도루,도실,타율,OBP,SLG
0,2017,나성범,NC,125,561,498,173,105,42,2,...,12,116,3,3,8,17,7,0.347,0.415330,0.584337
1,2017,박민우,NC,106,452,388,141,109,25,4,...,11,51,4,7,8,11,1,0.363,0.440980,0.471649
2,2017,스크럭스,NC,115,518,437,131,72,24,0,...,12,134,4,4,8,4,0,0.3,0.401544,0.594966
3,2017,손시헌,NC,124,391,349,122,99,17,1,...,8,44,5,18,5,1,0,0.35,0.386243,0.446991
4,2017,권희동,NC,141,554,472,135,94,20,2,...,16,90,7,14,12,3,3,0.286,0.371115,0.457627
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2021,최승민,NC,48,34,31,7,6,1,0,...,0,7,0,2,0,4,3,0.226,0.250000,0.258065
155,2021,정진기,NC,86,199,186,43,29,8,0,...,1,37,0,2,2,6,3,0.231,0.274112,0.370968
156,2021,김기환,NC,62,149,140,29,17,7,2,...,0,45,0,1,1,15,3,0.207,0.250000,0.350000
157,2021,박대온,NC,42,95,85,18,17,1,0,...,0,21,2,6,0,0,0,0.212,0.241758,0.223529
158,2021,이원재,NC,31,69,65,15,13,2,0,...,1,11,1,2,1,1,0,0.231,0.250000,0.261538

#### OPS = 출루율 + 장타율

In [10]:
bat_19['OPS'] = [k + l for k, l in zip(bat_19['OBP'], bat_19['SLG'])]
bat_19

,연도,선수명,팀명,경기,타석,타수,안타,단타,2루타,3루타,...,삼진,희플,희타,병살,도루,도실,타율,OBP,SLG,OPS
0,2017,나성범,NC,125,561,498,173,105,42,2,...,116,3,3,8,17,7,0.347,0.415330,0.584337,0.999667
1,2017,박민우,NC,106,452,388,141,109,25,4,...,51,4,7,8,11,1,0.363,0.440980,0.471649,0.912629
2,2017,스크럭스,NC,115,518,437,131,72,24,0,...,134,4,4,8,4,0,0.3,0.401544,0.594966,0.996510
3,2017,손시헌,NC,124,391,349,122,99,17,1,...,44,5,18,5,1,0,0.35,0.386243,0.446991,0.833235
4,2017,권희동,NC,141,554,472,135,94,20,2,...,90,7,14,12,3,3,0.286,0.371115,0.457627,0.828742
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2021,최승민,NC,48,34,31,7,6,1,0,...,7,0,2,0,4,3,0.226,0.250000,0.258065,0.508065
155,2021,정진기,NC,86,199,186,43,29,8,0,...,37,0,2,2,6,3,0.231,0.274112,0.370968,0.645079
156,2021,김기환,NC,62,149,140,29,17,7,2,...,45,0,1,1,15,3,0.207,0.250000,0.350000,0.600000
157,2021,박대온,NC,42,95,85,18,17,1,0,...,21,2,6,0,0,0,0.212,0.241758,0.223529,0.465288
158,2021,이원재,NC,31,69,65,15,13,2,0,...,11,1,2,1,1,0,0.231,0.250000,0.261538,0.511538

### GPA(Gleeman Production Average, Gross Production Average)
((출루율×1.8) + 장타율) / 4
기존 OPS 수치를 보정함 출루율이 장타율 보다 80% 더 중요하다고 해서

In [11]:
bat_19

,연도,선수명,팀명,경기,타석,타수,안타,단타,2루타,3루타,...,삼진,희플,희타,병살,도루,도실,타율,OBP,SLG,OPS
0,2017,나성범,NC,125,561,498,173,105,42,2,...,116,3,3,8,17,7,0.347,0.415330,0.584337,0.999667
1,2017,박민우,NC,106,452,388,141,109,25,4,...,51,4,7,8,11,1,0.363,0.440980,0.471649,0.912629
2,2017,스크럭스,NC,115,518,437,131,72,24,0,...,134,4,4,8,4,0,0.3,0.401544,0.594966,0.996510
3,2017,손시헌,NC,124,391,349,122,99,17,1,...,44,5,18,5,1,0,0.35,0.386243,0.446991,0.833235
4,2017,권희동,NC,141,554,472,135,94,20,2,...,90,7,14,12,3,3,0.286,0.371115,0.457627,0.828742
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2021,최승민,NC,48,34,31,7,6,1,0,...,7,0,2,0,4,3,0.226,0.250000,0.258065,0.508065
155,2021,정진기,NC,86,199,186,43,29,8,0,...,37,0,2,2,6,3,0.231,0.274112,0.370968,0.645079
156,2021,김기환,NC,62,149,140,29,17,7,2,...,45,0,1,1,15,3,0.207,0.250000,0.350000,0.600000
157,2021,박대온,NC,42,95,85,18,17,1,0,...,21,2,6,0,0,0,0.212,0.241758,0.223529,0.465288
158,2021,이원재,NC,31,69,65,15,13,2,0,...,11,1,2,1,1,0,0.231,0.250000,0.261538,0.511538

In [12]:
GPA_list = [(bat_19['OBP'][m] * 1.8 + bat_19['SLG'][m]) / 4 for m in range(0, len(bat_19))]
bat_19['GPA'] = GPA_list
bat_19

,연도,선수명,팀명,경기,타석,타수,안타,단타,2루타,3루타,...,희플,희타,병살,도루,도실,타율,OBP,SLG,OPS,GPA
0,2017,나성범,NC,125,561,498,173,105,42,2,...,3,3,8,17,7,0.347,0.415330,0.584337,0.999667,0.332983
1,2017,박민우,NC,106,452,388,141,109,25,4,...,4,7,8,11,1,0.363,0.440980,0.471649,0.912629,0.316353
2,2017,스크럭스,NC,115,518,437,131,72,24,0,...,4,4,8,4,0,0.3,0.401544,0.594966,0.996510,0.329436
3,2017,손시헌,NC,124,391,349,122,99,17,1,...,5,18,5,1,0,0.35,0.386243,0.446991,0.833235,0.285557
4,2017,권희동,NC,141,554,472,135,94,20,2,...,7,14,12,3,3,0.286,0.371115,0.457627,0.828742,0.281409
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2021,최승민,NC,48,34,31,7,6,1,0,...,0,2,0,4,3,0.226,0.250000,0.258065,0.508065,0.177016
155,2021,정진기,NC,86,199,186,43,29,8,0,...,0,2,2,6,3,0.231,0.274112,0.370968,0.645079,0.216092
156,2021,김기환,NC,62,149,140,29,17,7,2,...,0,1,1,15,3,0.207,0.250000,0.350000,0.600000,0.200000
157,2021,박대온,NC,42,95,85,18,17,1,0,...,2,6,0,0,0,0.212,0.241758,0.223529,0.465288,0.164674
158,2021,이원재,NC,31,69,65,15,13,2,0,...,1,2,1,1,0,0.231,0.250000,0.261538,0.511538,0.177885

### SECA (Secondary Average)
SECA = (BB + (TB - H) + (SB -CS)) / AB

In [13]:
SecA는 루타에서 단타를 빼 추가 진루를 얼마나 얻어냈는지 보는 스탯입니다. 
타율은 장타가 구분되지 않고 볼넷이 포함되지 않기 때문에 타율로  평가할 수 없는 부분인 장타력과 
선구안을 보는 것입니다. 분자에 볼넷이 들어가는데 분모에는 볼넷이 포함되지 않는 문제가 있습니다.
단타가 빠지기 때문에 SecA 만으로는 종합적인 타격능력을 평가할 수는 없고 타율의 보조적인 역할을 합니다.
리그평균 SecA는 0.200 ~ 0.250 정도입니다.

SyntaxError: invalid syntax (<ipython-input-13-2c8de78badc8>, line 1)

In [14]:
bat_19

,연도,선수명,팀명,경기,타석,타수,안타,단타,2루타,3루타,...,희플,희타,병살,도루,도실,타율,OBP,SLG,OPS,GPA
0,2017,나성범,NC,125,561,498,173,105,42,2,...,3,3,8,17,7,0.347,0.415330,0.584337,0.999667,0.332983
1,2017,박민우,NC,106,452,388,141,109,25,4,...,4,7,8,11,1,0.363,0.440980,0.471649,0.912629,0.316353
2,2017,스크럭스,NC,115,518,437,131,72,24,0,...,4,4,8,4,0,0.3,0.401544,0.594966,0.996510,0.329436
3,2017,손시헌,NC,124,391,349,122,99,17,1,...,5,18,5,1,0,0.35,0.386243,0.446991,0.833235,0.285557
4,2017,권희동,NC,141,554,472,135,94,20,2,...,7,14,12,3,3,0.286,0.371115,0.457627,0.828742,0.281409
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2021,최승민,NC,48,34,31,7,6,1,0,...,0,2,0,4,3,0.226,0.250000,0.258065,0.508065,0.177016
155,2021,정진기,NC,86,199,186,43,29,8,0,...,0,2,2,6,3,0.231,0.274112,0.370968,0.645079,0.216092
156,2021,김기환,NC,62,149,140,29,17,7,2,...,0,1,1,15,3,0.207,0.250000,0.350000,0.600000,0.200000
157,2021,박대온,NC,42,95,85,18,17,1,0,...,2,6,0,0,0,0.212,0.241758,0.223529,0.465288,0.164674
158,2021,이원재,NC,31,69,65,15,13,2,0,...,1,2,1,1,0,0.231,0.250000,0.261538,0.511538,0.177885

In [15]:
## TB(Total Base) = 총 루타수
TB_list = [HIT1[n] + HIT2[n]*2 + HIT3[n]*3 + HR[n]*4 for n in range(0, len(bat_19))]
SECA_list = [(BB[o] + TB_list[o] - HIT1[o] + SB[o] - CS[o]) /
              AB[o] for o in range(0, len(bat_19))]
bat_19['SECA'] = SECA_list
bat_19

<ipython-input-15-489c13f7778f>:3: RuntimeWarning: invalid value encountered in longlong_scalars
  SECA_list = [(BB[o] + TB_list[o] - HIT1[o] + SB[o] - CS[o]) /

,연도,선수명,팀명,경기,타석,타수,안타,단타,2루타,3루타,...,희타,병살,도루,도실,타율,OBP,SLG,OPS,GPA,SECA
0,2017,나성범,NC,125,561,498,173,105,42,2,...,3,8,17,7,0.347,0.415330,0.584337,0.999667,0.332983,0.489960
1,2017,박민우,NC,106,452,388,141,109,25,4,...,7,8,11,1,0.363,0.440980,0.471649,0.912629,0.316353,0.335052
2,2017,스크럭스,NC,115,518,437,131,72,24,0,...,4,8,4,0,0.3,0.401544,0.594966,0.996510,0.329436,0.588101
3,2017,손시헌,NC,124,391,349,122,99,17,1,...,18,5,1,0,0.35,0.386243,0.446991,0.833235,0.285557,0.212034
4,2017,권희동,NC,141,554,472,135,94,20,2,...,14,12,3,3,0.286,0.371115,0.457627,0.828742,0.281409,0.368644
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2021,최승민,NC,48,34,31,7,6,1,0,...,2,0,4,3,0.226,0.250000,0.258065,0.508065,0.177016,0.129032
155,2021,정진기,NC,86,199,186,43,29,8,0,...,2,2,6,3,0.231,0.274112,0.370968,0.645079,0.216092,0.284946
156,2021,김기환,NC,62,149,140,29,17,7,2,...,1,1,15,3,0.207,0.250000,0.350000,0.600000,0.200000,0.371429
157,2021,박대온,NC,42,95,85,18,17,1,0,...,6,0,0,0,0.212,0.241758,0.223529,0.465288,0.164674,0.070588
158,2021,이원재,NC,31,69,65,15,13,2,0,...,2,1,1,0,0.231,0.250000,0.261538,0.511538,0.177885,0.092308

### TA
TA shows a batter’s offensive contribution. The higher the number, the more contributions and the fewer negative contributions.

In [16]:
TA = (Total Bases + Hit by Pitch + Walks + Stolen Base) ÷ 
(At Bats – Hits + Caught Stealing + Ground Into Double Play)

SyntaxError: invalid syntax (<ipython-input-16-dc8e251db19d>, line 1)

In [17]:
bat_19

,연도,선수명,팀명,경기,타석,타수,안타,단타,2루타,3루타,...,희타,병살,도루,도실,타율,OBP,SLG,OPS,GPA,SECA
0,2017,나성범,NC,125,561,498,173,105,42,2,...,3,8,17,7,0.347,0.415330,0.584337,0.999667,0.332983,0.489960
1,2017,박민우,NC,106,452,388,141,109,25,4,...,7,8,11,1,0.363,0.440980,0.471649,0.912629,0.316353,0.335052
2,2017,스크럭스,NC,115,518,437,131,72,24,0,...,4,8,4,0,0.3,0.401544,0.594966,0.996510,0.329436,0.588101
3,2017,손시헌,NC,124,391,349,122,99,17,1,...,18,5,1,0,0.35,0.386243,0.446991,0.833235,0.285557,0.212034
4,2017,권희동,NC,141,554,472,135,94,20,2,...,14,12,3,3,0.286,0.371115,0.457627,0.828742,0.281409,0.368644
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2021,최승민,NC,48,34,31,7,6,1,0,...,2,0,4,3,0.226,0.250000,0.258065,0.508065,0.177016,0.129032
155,2021,정진기,NC,86,199,186,43,29,8,0,...,2,2,6,3,0.231,0.274112,0.370968,0.645079,0.216092,0.284946
156,2021,김기환,NC,62,149,140,29,17,7,2,...,1,1,15,3,0.207,0.250000,0.350000,0.600000,0.200000,0.371429
157,2021,박대온,NC,42,95,85,18,17,1,0,...,6,0,0,0,0.212,0.241758,0.223529,0.465288,0.164674,0.070588
158,2021,이원재,NC,31,69,65,15,13,2,0,...,2,1,1,0,0.231,0.250000,0.261538,0.511538,0.177885,0.092308

In [18]:
## 총 루타수는 위에서 구한 TB_list 사용
TA_list = [(TB_list[q] + HP[q] + BB[q] + SB[q]) /
           (AB[q] - HIT[q] + CS[q] + GD[q]) for q in range(0, len(bat_19))]
bat_19['TA'] = TA_list
bat_19

<ipython-input-18-f5b56fa45672>:2: RuntimeWarning: invalid value encountered in longlong_scalars
  TA_list = [(TB_list[q] + HP[q] + BB[q] + SB[q]) /

,연도,선수명,팀명,경기,타석,타수,안타,단타,2루타,3루타,...,병살,도루,도실,타율,OBP,SLG,OPS,GPA,SECA,TA
0,2017,나성범,NC,125,561,498,173,105,42,2,...,8,17,7,0.347,0.415330,0.584337,0.999667,0.332983,0.489960,1.082353
1,2017,박민우,NC,106,452,388,141,109,25,4,...,8,11,1,0.363,0.440980,0.471649,0.912629,0.316353,0.335052,0.980469
2,2017,스크럭스,NC,115,518,437,131,72,24,0,...,8,4,0,0.3,0.401544,0.594966,0.996510,0.329436,0.588101,1.085987
3,2017,손시헌,NC,124,391,349,122,99,17,1,...,5,1,0,0.35,0.386243,0.446991,0.833235,0.285557,0.212034,0.780172
4,2017,권희동,NC,141,554,472,135,94,20,2,...,12,3,3,0.286,0.371115,0.457627,0.828742,0.281409,0.368644,0.815341
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2021,최승민,NC,48,34,31,7,6,1,0,...,0,4,3,0.226,0.250000,0.258065,0.508065,0.177016,0.129032,0.481481
155,2021,정진기,NC,86,199,186,43,29,8,0,...,2,6,3,0.231,0.274112,0.370968,0.645079,0.216092,0.284946,0.581081
156,2021,김기환,NC,62,149,140,29,17,7,2,...,1,15,3,0.207,0.250000,0.350000,0.600000,0.200000,0.371429,0.626087
157,2021,박대온,NC,42,95,85,18,17,1,0,...,0,0,0,0.212,0.241758,0.223529,0.465288,0.164674,0.070588,0.343284
158,2021,이원재,NC,31,69,65,15,13,2,0,...,1,1,0,0.231,0.250000,0.261538,0.511538,0.177885,0.092308,0.392157

### RC
빌 제임스가 고안한 한 타자가 (어떤 방식으로든) 만들어낸 득점 생산력. 당연히 높을수록 팀의 승리에 기여하는 바가 크다. 각 숫자들은 득점에 각 항목이 어느 정도 기여했는지를 알려주는 것이라 이해하면 된다. 예를 들면 도루가 0.62라는 것은 도루 한 개가 0.62점에 해당한다는 뜻.

In [19]:
A: 안타 + 볼넷 - 도루실패 + 몸에맞는공 - 병살타
B: (1.125×단타) + (1.69 x 2루타) + (3.02×3루타) + (3.73×홈런) + .29×(BB-IBB+HBP) + .492×(SH+SF+SB) - (0.4×K)
C: 타수 + 볼넷 + 몸에맞는 공 + 희생번트 + 희생플라이
((2.4C + A)*(3C + B)) / 9C - 0.9C
추가사항 + 득점권 안타 수 - (득점권 타수 * 타율) + 주자 있을 때 홈런 - (주자 있을 때 타수 * 홈런) / 타수
    주자 있을 때 홈런이랑 타수를 어떻게 알아내냐고??????

SyntaxError: invalid character in identifier (<ipython-input-19-06aa3c99a8a2>, line 2)

In [20]:
bat_19

,연도,선수명,팀명,경기,타석,타수,안타,단타,2루타,3루타,...,병살,도루,도실,타율,OBP,SLG,OPS,GPA,SECA,TA
0,2017,나성범,NC,125,561,498,173,105,42,2,...,8,17,7,0.347,0.415330,0.584337,0.999667,0.332983,0.489960,1.082353
1,2017,박민우,NC,106,452,388,141,109,25,4,...,8,11,1,0.363,0.440980,0.471649,0.912629,0.316353,0.335052,0.980469
2,2017,스크럭스,NC,115,518,437,131,72,24,0,...,8,4,0,0.3,0.401544,0.594966,0.996510,0.329436,0.588101,1.085987
3,2017,손시헌,NC,124,391,349,122,99,17,1,...,5,1,0,0.35,0.386243,0.446991,0.833235,0.285557,0.212034,0.780172
4,2017,권희동,NC,141,554,472,135,94,20,2,...,12,3,3,0.286,0.371115,0.457627,0.828742,0.281409,0.368644,0.815341
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2021,최승민,NC,48,34,31,7,6,1,0,...,0,4,3,0.226,0.250000,0.258065,0.508065,0.177016,0.129032,0.481481
155,2021,정진기,NC,86,199,186,43,29,8,0,...,2,6,3,0.231,0.274112,0.370968,0.645079,0.216092,0.284946,0.581081
156,2021,김기환,NC,62,149,140,29,17,7,2,...,1,15,3,0.207,0.250000,0.350000,0.600000,0.200000,0.371429,0.626087
157,2021,박대온,NC,42,95,85,18,17,1,0,...,0,0,0,0.212,0.241758,0.223529,0.465288,0.164674,0.070588,0.343284
158,2021,이원재,NC,31,69,65,15,13,2,0,...,1,1,0,0.231,0.250000,0.261538,0.511538,0.177885,0.092308,0.392157

In [21]:
RC_list = []
for r in range(0, len(bat_19)) :
    A = HIT[r] + BB[r] - CS[r] + HP[r] - GD[r]
    B = ((1.125 * HIT1[r]) + (1.69 * HIT2[r]) + (3.02 * HIT3[r]) + (3.73 * HR[r]) + 
         (0.29 * (BB[r] - IB[r] + HP[r])) + (0.492 * (SH[r] + SF[r] + SB[r])) - (0.4 * KK[r]))
    C = AB[r] + BB[r] + HP[r] + SH[r] + SF[r]
    RC_list.append((((2.4 * C) + A) * ((3 * C) + B)) / (9 * C) - (0.9 * C))

<ipython-input-21-ea10fbbfc9f8>:7: RuntimeWarning: invalid value encountered in double_scalars
  RC_list.append((((2.4 * C) + A) * ((3 * C) + B)) / (9 * C) - (0.9 * C))

In [22]:
bat_19['RC'] = RC_list
bat_19

,연도,선수명,팀명,경기,타석,타수,안타,단타,2루타,3루타,...,도루,도실,타율,OBP,SLG,OPS,GPA,SECA,TA,RC
0,2017,나성범,NC,125,561,498,173,105,42,2,...,17,7,0.347,0.415330,0.584337,0.999667,0.332983,0.489960,1.082353,98.029807
1,2017,박민우,NC,106,452,388,141,109,25,4,...,11,1,0.363,0.440980,0.471649,0.912629,0.316353,0.335052,0.980469,78.411222
2,2017,스크럭스,NC,115,518,437,131,72,24,0,...,4,0,0.3,0.401544,0.594966,0.996510,0.329436,0.588101,1.085987,84.405164
3,2017,손시헌,NC,124,391,349,122,99,17,1,...,1,0,0.35,0.386243,0.446991,0.833235,0.285557,0.212034,0.780172,57.209058
4,2017,권희동,NC,141,554,472,135,94,20,2,...,3,3,0.286,0.371115,0.457627,0.828742,0.281409,0.368644,0.815341,70.902062
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2021,최승민,NC,48,34,31,7,6,1,0,...,4,3,0.226,0.250000,0.258065,0.508065,0.177016,0.129032,0.481481,0.780331
155,2021,정진기,NC,86,199,186,43,29,8,0,...,6,3,0.231,0.274112,0.370968,0.645079,0.216092,0.284946,0.581081,14.325090
156,2021,김기환,NC,62,149,140,29,17,7,2,...,15,3,0.207,0.250000,0.350000,0.600000,0.200000,0.371429,0.626087,7.860817
157,2021,박대온,NC,42,95,85,18,17,1,0,...,0,0,0.212,0.241758,0.223529,0.465288,0.164674,0.070588,0.343284,2.744219
158,2021,이원재,NC,31,69,65,15,13,2,0,...,1,0,0.231,0.250000,0.261538,0.511538,0.177885,0.092308,0.392157,3.051035

### RC/27
경기당 득점 기대치. 27아웃당(27타석이 아니다) RC. 27아웃은 한 경기를 가리킨다. 즉, 한 타자를 8명 더 복제해서 1번부터 9번까지 전부 그 타자로만 채웠을 때, 그 팀이 몇 점을 얻을 수 있느냐-라고 이해하면 된다.

In [23]:
bat_19

,연도,선수명,팀명,경기,타석,타수,안타,단타,2루타,3루타,...,도루,도실,타율,OBP,SLG,OPS,GPA,SECA,TA,RC
0,2017,나성범,NC,125,561,498,173,105,42,2,...,17,7,0.347,0.415330,0.584337,0.999667,0.332983,0.489960,1.082353,98.029807
1,2017,박민우,NC,106,452,388,141,109,25,4,...,11,1,0.363,0.440980,0.471649,0.912629,0.316353,0.335052,0.980469,78.411222
2,2017,스크럭스,NC,115,518,437,131,72,24,0,...,4,0,0.3,0.401544,0.594966,0.996510,0.329436,0.588101,1.085987,84.405164
3,2017,손시헌,NC,124,391,349,122,99,17,1,...,1,0,0.35,0.386243,0.446991,0.833235,0.285557,0.212034,0.780172,57.209058
4,2017,권희동,NC,141,554,472,135,94,20,2,...,3,3,0.286,0.371115,0.457627,0.828742,0.281409,0.368644,0.815341,70.902062
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2021,최승민,NC,48,34,31,7,6,1,0,...,4,3,0.226,0.250000,0.258065,0.508065,0.177016,0.129032,0.481481,0.780331
155,2021,정진기,NC,86,199,186,43,29,8,0,...,6,3,0.231,0.274112,0.370968,0.645079,0.216092,0.284946,0.581081,14.325090
156,2021,김기환,NC,62,149,140,29,17,7,2,...,15,3,0.207,0.250000,0.350000,0.600000,0.200000,0.371429,0.626087,7.860817
157,2021,박대온,NC,42,95,85,18,17,1,0,...,0,0,0.212,0.241758,0.223529,0.465288,0.164674,0.070588,0.343284,2.744219
158,2021,이원재,NC,31,69,65,15,13,2,0,...,1,0,0.231,0.250000,0.261538,0.511538,0.177885,0.092308,0.392157,3.051035

In [24]:
RC27_list = []
for t in bat_19['RC'] :
    RC27_list.append(t/27)
bat_19['RC27'] = RC27_list
bat_19

,연도,선수명,팀명,경기,타석,타수,안타,단타,2루타,3루타,...,도실,타율,OBP,SLG,OPS,GPA,SECA,TA,RC,RC27
0,2017,나성범,NC,125,561,498,173,105,42,2,...,7,0.347,0.415330,0.584337,0.999667,0.332983,0.489960,1.082353,98.029807,3.630734
1,2017,박민우,NC,106,452,388,141,109,25,4,...,1,0.363,0.440980,0.471649,0.912629,0.316353,0.335052,0.980469,78.411222,2.904119
2,2017,스크럭스,NC,115,518,437,131,72,24,0,...,0,0.3,0.401544,0.594966,0.996510,0.329436,0.588101,1.085987,84.405164,3.126117
3,2017,손시헌,NC,124,391,349,122,99,17,1,...,0,0.35,0.386243,0.446991,0.833235,0.285557,0.212034,0.780172,57.209058,2.118854
4,2017,권희동,NC,141,554,472,135,94,20,2,...,3,0.286,0.371115,0.457627,0.828742,0.281409,0.368644,0.815341,70.902062,2.626002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2021,최승민,NC,48,34,31,7,6,1,0,...,3,0.226,0.250000,0.258065,0.508065,0.177016,0.129032,0.481481,0.780331,0.028901
155,2021,정진기,NC,86,199,186,43,29,8,0,...,3,0.231,0.274112,0.370968,0.645079,0.216092,0.284946,0.581081,14.325090,0.530559
156,2021,김기환,NC,62,149,140,29,17,7,2,...,3,0.207,0.250000,0.350000,0.600000,0.200000,0.371429,0.626087,7.860817,0.291141
157,2021,박대온,NC,42,95,85,18,17,1,0,...,0,0.212,0.241758,0.223529,0.465288,0.164674,0.070588,0.343284,2.744219,0.101638
158,2021,이원재,NC,31,69,65,15,13,2,0,...,0,0.231,0.250000,0.261538,0.511538,0.177885,0.092308,0.392157,3.051035,0.113001

### XR
RC보다 복잡하지만 좀 더 정확한 스탯으로 알려져 있다.

In [25]:
1루타×0.5 + 2루타×0.72 + 3루타×1.04 + 홈런×1.44 + (몸에 맞는 볼 + 볼넷 - 고의4구)×0.34 +
고의4구×0.25 + 도루×0.18 - 도루실패×0.32 - (타수 - 안타 - 삼진)×0.09 - 삼진×0.098 -
병살타×0.37 + 희생플라이×0.37 + 희생번트×0.04.

SyntaxError: invalid character in identifier (<ipython-input-25-b177d958fe4e>, line 1)

In [26]:
XR_list = []
for s in range(0, len(bat_19)) :
    XR_list.append(((HIT1[s] * 0.5) + (HIT2[s] * 0.72) + (HIT3[s] * 1.04) + (HR[s] * 1.44) + 
          ((HP[s] + BB[s] - IB[s]) * 0.34) + (IB[s] * 0.25) + (SB[s] * 0.18) - (CS[s] * 0.32) -
          ((AB[s] - HIT[s] - KK[s]) * 0.09) - (KK[s] * 0.098) - (GD[s] * 0.37) +
          (SF[s] * 0.37) + (SH[s] * 0.04)))

In [27]:
bat_19['XR'] = XR_list
bat_19

,연도,선수명,팀명,경기,타석,타수,안타,단타,2루타,3루타,...,타율,OBP,SLG,OPS,GPA,SECA,TA,RC,RC27,XR
0,2017,나성범,NC,125,561,498,173,105,42,2,...,0.347,0.415330,0.584337,0.999667,0.332983,0.489960,1.082353,98.029807,3.630734,107.792
1,2017,박민우,NC,106,452,388,141,109,25,4,...,0.363,0.440980,0.471649,0.912629,0.316353,0.335052,0.980469,78.411222,2.904119,78.182
2,2017,스크럭스,NC,115,518,437,131,72,24,0,...,0.3,0.401544,0.594966,0.996510,0.329436,0.588101,1.085987,84.405164,3.126117,100.468
3,2017,손시헌,NC,124,391,349,122,99,17,1,...,0.35,0.386243,0.446991,0.833235,0.285557,0.212034,0.780172,57.209058,2.118854,58.168
4,2017,권희동,NC,141,554,472,135,94,20,2,...,0.286,0.371115,0.457627,0.828742,0.281409,0.368644,0.815341,70.902062,2.626002,81.110
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2021,최승민,NC,48,34,31,7,6,1,0,...,0.226,0.250000,0.258065,0.508065,0.177016,0.129032,0.481481,0.780331,0.028901,1.684
155,2021,정진기,NC,86,199,186,43,29,8,0,...,0.231,0.274112,0.370968,0.645079,0.216092,0.284946,0.581081,14.325090,0.530559,18.934
156,2021,김기환,NC,62,149,140,29,17,7,2,...,0.207,0.250000,0.350000,0.600000,0.200000,0.371429,0.626087,7.860817,0.291141,13.720
157,2021,박대온,NC,42,95,85,18,17,1,0,...,0.212,0.241758,0.223529,0.465288,0.164674,0.070588,0.343284,2.744219,0.101638,5.362
158,2021,이원재,NC,31,69,65,15,13,2,0,...,0.231,0.250000,0.261538,0.511538,0.177885,0.092308,0.392157,3.051035,0.113001,4.292

### ISO (Isolated Power)
ISO = SLG – AVG

In [28]:
bat_19

,연도,선수명,팀명,경기,타석,타수,안타,단타,2루타,3루타,...,타율,OBP,SLG,OPS,GPA,SECA,TA,RC,RC27,XR
0,2017,나성범,NC,125,561,498,173,105,42,2,...,0.347,0.415330,0.584337,0.999667,0.332983,0.489960,1.082353,98.029807,3.630734,107.792
1,2017,박민우,NC,106,452,388,141,109,25,4,...,0.363,0.440980,0.471649,0.912629,0.316353,0.335052,0.980469,78.411222,2.904119,78.182
2,2017,스크럭스,NC,115,518,437,131,72,24,0,...,0.3,0.401544,0.594966,0.996510,0.329436,0.588101,1.085987,84.405164,3.126117,100.468
3,2017,손시헌,NC,124,391,349,122,99,17,1,...,0.35,0.386243,0.446991,0.833235,0.285557,0.212034,0.780172,57.209058,2.118854,58.168
4,2017,권희동,NC,141,554,472,135,94,20,2,...,0.286,0.371115,0.457627,0.828742,0.281409,0.368644,0.815341,70.902062,2.626002,81.110
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2021,최승민,NC,48,34,31,7,6,1,0,...,0.226,0.250000,0.258065,0.508065,0.177016,0.129032,0.481481,0.780331,0.028901,1.684
155,2021,정진기,NC,86,199,186,43,29,8,0,...,0.231,0.274112,0.370968,0.645079,0.216092,0.284946,0.581081,14.325090,0.530559,18.934
156,2021,김기환,NC,62,149,140,29,17,7,2,...,0.207,0.250000,0.350000,0.600000,0.200000,0.371429,0.626087,7.860817,0.291141,13.720
157,2021,박대온,NC,42,95,85,18,17,1,0,...,0.212,0.241758,0.223529,0.465288,0.164674,0.070588,0.343284,2.744219,0.101638,5.362
158,2021,이원재,NC,31,69,65,15,13,2,0,...,0.231,0.250000,0.261538,0.511538,0.177885,0.092308,0.392157,3.051035,0.113001,4.292

In [29]:
ISO_list = []
for u, v in enumerate(bat_19['SLG']) :
    SLG = v
    AVG = (HIT[u] / AB[u])
    ISO_list.append(SLG - AVG)
bat_19['ISO'] = ISO_list
bat_19

<ipython-input-29-f2d769b82ab0>:4: RuntimeWarning: invalid value encountered in longlong_scalars
  AVG = (HIT[u] / AB[u])

,연도,선수명,팀명,경기,타석,타수,안타,단타,2루타,3루타,...,OBP,SLG,OPS,GPA,SECA,TA,RC,RC27,XR,ISO
0,2017,나성범,NC,125,561,498,173,105,42,2,...,0.415330,0.584337,0.999667,0.332983,0.489960,1.082353,98.029807,3.630734,107.792,0.236948
1,2017,박민우,NC,106,452,388,141,109,25,4,...,0.440980,0.471649,0.912629,0.316353,0.335052,0.980469,78.411222,2.904119,78.182,0.108247
2,2017,스크럭스,NC,115,518,437,131,72,24,0,...,0.401544,0.594966,0.996510,0.329436,0.588101,1.085987,84.405164,3.126117,100.468,0.295195
3,2017,손시헌,NC,124,391,349,122,99,17,1,...,0.386243,0.446991,0.833235,0.285557,0.212034,0.780172,57.209058,2.118854,58.168,0.097421
4,2017,권희동,NC,141,554,472,135,94,20,2,...,0.371115,0.457627,0.828742,0.281409,0.368644,0.815341,70.902062,2.626002,81.110,0.171610
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2021,최승민,NC,48,34,31,7,6,1,0,...,0.250000,0.258065,0.508065,0.177016,0.129032,0.481481,0.780331,0.028901,1.684,0.032258
155,2021,정진기,NC,86,199,186,43,29,8,0,...,0.274112,0.370968,0.645079,0.216092,0.284946,0.581081,14.325090,0.530559,18.934,0.139785
156,2021,김기환,NC,62,149,140,29,17,7,2,...,0.250000,0.350000,0.600000,0.200000,0.371429,0.626087,7.860817,0.291141,13.720,0.142857
157,2021,박대온,NC,42,95,85,18,17,1,0,...,0.241758,0.223529,0.465288,0.164674,0.070588,0.343284,2.744219,0.101638,5.362,0.011765
158,2021,이원재,NC,31,69,65,15,13,2,0,...,0.250000,0.261538,0.511538,0.177885,0.092308,0.392157,3.051035,0.113001,4.292,0.030769

### PSN (Power Speed Number)
PSR = (2 * HR * SB) / (HR+SB)
호타준족? 장타도 잘치고 잘 뛰는

In [30]:
bat_19

,연도,선수명,팀명,경기,타석,타수,안타,단타,2루타,3루타,...,OBP,SLG,OPS,GPA,SECA,TA,RC,RC27,XR,ISO
0,2017,나성범,NC,125,561,498,173,105,42,2,...,0.415330,0.584337,0.999667,0.332983,0.489960,1.082353,98.029807,3.630734,107.792,0.236948
1,2017,박민우,NC,106,452,388,141,109,25,4,...,0.440980,0.471649,0.912629,0.316353,0.335052,0.980469,78.411222,2.904119,78.182,0.108247
2,2017,스크럭스,NC,115,518,437,131,72,24,0,...,0.401544,0.594966,0.996510,0.329436,0.588101,1.085987,84.405164,3.126117,100.468,0.295195
3,2017,손시헌,NC,124,391,349,122,99,17,1,...,0.386243,0.446991,0.833235,0.285557,0.212034,0.780172,57.209058,2.118854,58.168,0.097421
4,2017,권희동,NC,141,554,472,135,94,20,2,...,0.371115,0.457627,0.828742,0.281409,0.368644,0.815341,70.902062,2.626002,81.110,0.171610
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2021,최승민,NC,48,34,31,7,6,1,0,...,0.250000,0.258065,0.508065,0.177016,0.129032,0.481481,0.780331,0.028901,1.684,0.032258
155,2021,정진기,NC,86,199,186,43,29,8,0,...,0.274112,0.370968,0.645079,0.216092,0.284946,0.581081,14.325090,0.530559,18.934,0.139785
156,2021,김기환,NC,62,149,140,29,17,7,2,...,0.250000,0.350000,0.600000,0.200000,0.371429,0.626087,7.860817,0.291141,13.720,0.142857
157,2021,박대온,NC,42,95,85,18,17,1,0,...,0.241758,0.223529,0.465288,0.164674,0.070588,0.343284,2.744219,0.101638,5.362,0.011765
158,2021,이원재,NC,31,69,65,15,13,2,0,...,0.250000,0.261538,0.511538,0.177885,0.092308,0.392157,3.051035,0.113001,4.292,0.030769

In [31]:
PSN_list = []
for w in range(0, len(bat_19)) :
    PSN_list.append((2 * HR[w] * SB[w]) / (HR[w] + SB[w]))
bat_19['PSN'] = PSN_list
bat_19

<ipython-input-31-1c34f2097d02>:3: RuntimeWarning: invalid value encountered in longlong_scalars
  PSN_list.append((2 * HR[w] * SB[w]) / (HR[w] + SB[w]))

,연도,선수명,팀명,경기,타석,타수,안타,단타,2루타,3루타,...,SLG,OPS,GPA,SECA,TA,RC,RC27,XR,ISO,PSN
0,2017,나성범,NC,125,561,498,173,105,42,2,...,0.584337,0.999667,0.332983,0.489960,1.082353,98.029807,3.630734,107.792,0.236948,19.902439
1,2017,박민우,NC,106,452,388,141,109,25,4,...,0.471649,0.912629,0.316353,0.335052,0.980469,78.411222,2.904119,78.182,0.108247,4.714286
2,2017,스크럭스,NC,115,518,437,131,72,24,0,...,0.594966,0.996510,0.329436,0.588101,1.085987,84.405164,3.126117,100.468,0.295195,7.179487
3,2017,손시헌,NC,124,391,349,122,99,17,1,...,0.446991,0.833235,0.285557,0.212034,0.780172,57.209058,2.118854,58.168,0.097421,1.666667
4,2017,권희동,NC,141,554,472,135,94,20,2,...,0.457627,0.828742,0.281409,0.368644,0.815341,70.902062,2.626002,81.110,0.171610,5.181818
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2021,최승민,NC,48,34,31,7,6,1,0,...,0.258065,0.508065,0.177016,0.129032,0.481481,0.780331,0.028901,1.684,0.032258,0.000000
155,2021,정진기,NC,86,199,186,43,29,8,0,...,0.370968,0.645079,0.216092,0.284946,0.581081,14.325090,0.530559,18.934,0.139785,6.000000
156,2021,김기환,NC,62,149,140,29,17,7,2,...,0.350000,0.600000,0.200000,0.371429,0.626087,7.860817,0.291141,13.720,0.142857,5.000000
157,2021,박대온,NC,42,95,85,18,17,1,0,...,0.223529,0.465288,0.164674,0.070588,0.343284,2.744219,0.101638,5.362,0.011765,NaN
158,2021,이원재,NC,31,69,65,15,13,2,0,...,0.261538,0.511538,0.177885,0.092308,0.392157,3.051035,0.113001,4.292,0.030769,0.000000

### wOBA (Weighted On Base Average) 가중 출루율

In [32]:
wOBA = (0.689×uBB + 0.722×HBP + 0.892×1B + 1.283×2B + 1.635×3B +
2.135×HR) / (AB + BB – IBB + SF + HBP)
uBB = unintentional base on balls

SyntaxError: invalid character in identifier (<ipython-input-32-020c8fdccb73>, line 1)

In [33]:
bat_19

,연도,선수명,팀명,경기,타석,타수,안타,단타,2루타,3루타,...,SLG,OPS,GPA,SECA,TA,RC,RC27,XR,ISO,PSN
0,2017,나성범,NC,125,561,498,173,105,42,2,...,0.584337,0.999667,0.332983,0.489960,1.082353,98.029807,3.630734,107.792,0.236948,19.902439
1,2017,박민우,NC,106,452,388,141,109,25,4,...,0.471649,0.912629,0.316353,0.335052,0.980469,78.411222,2.904119,78.182,0.108247,4.714286
2,2017,스크럭스,NC,115,518,437,131,72,24,0,...,0.594966,0.996510,0.329436,0.588101,1.085987,84.405164,3.126117,100.468,0.295195,7.179487
3,2017,손시헌,NC,124,391,349,122,99,17,1,...,0.446991,0.833235,0.285557,0.212034,0.780172,57.209058,2.118854,58.168,0.097421,1.666667
4,2017,권희동,NC,141,554,472,135,94,20,2,...,0.457627,0.828742,0.281409,0.368644,0.815341,70.902062,2.626002,81.110,0.171610,5.181818
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2021,최승민,NC,48,34,31,7,6,1,0,...,0.258065,0.508065,0.177016,0.129032,0.481481,0.780331,0.028901,1.684,0.032258,0.000000
155,2021,정진기,NC,86,199,186,43,29,8,0,...,0.370968,0.645079,0.216092,0.284946,0.581081,14.325090,0.530559,18.934,0.139785,6.000000
156,2021,김기환,NC,62,149,140,29,17,7,2,...,0.350000,0.600000,0.200000,0.371429,0.626087,7.860817,0.291141,13.720,0.142857,5.000000
157,2021,박대온,NC,42,95,85,18,17,1,0,...,0.223529,0.465288,0.164674,0.070588,0.343284,2.744219,0.101638,5.362,0.011765,NaN
158,2021,이원재,NC,31,69,65,15,13,2,0,...,0.261538,0.511538,0.177885,0.092308,0.392157,3.051035,0.113001,4.292,0.030769,0.000000

In [34]:
wOBA_list = []
for x in range(0, len(bat_19)) :
    wOBA_list.append(((0.689 * (BB[x] - IB[x]) + (0.722 * HP[x]) + (0.892 * HIT[x]) + 
                       (1.283 * HIT2[x]) + (1.635 * HIT[3]) + (2.135 * HR[x])) / 
                      (AB[x] + BB[x] - IB[x] + SF[x] + HP[x])))
bat_19['wOBA'] = wOBA_list
bat_19

<ipython-input-34-033f2270c0f2>:3: RuntimeWarning: divide by zero encountered in double_scalars
  wOBA_list.append(((0.689 * (BB[x] - IB[x]) + (0.722 * HP[x]) + (0.892 * HIT[x]) +

,연도,선수명,팀명,경기,타석,타수,안타,단타,2루타,3루타,...,OPS,GPA,SECA,TA,RC,RC27,XR,ISO,PSN,wOBA
0,2017,나성범,NC,125,561,498,173,105,42,2,...,0.999667,0.332983,0.489960,1.082353,98.029807,3.630734,107.792,0.236948,19.902439,0.896113
1,2017,박민우,NC,106,452,388,141,109,25,4,...,0.912629,0.316353,0.335052,0.980469,78.411222,2.904119,78.182,0.108247,4.714286,0.898347
2,2017,스크럭스,NC,115,518,437,131,72,24,0,...,0.996510,0.329436,0.588101,1.085987,84.405164,3.126117,100.468,0.295195,7.179487,0.918430
3,2017,손시헌,NC,124,391,349,122,99,17,1,...,0.833235,0.285557,0.212034,0.780172,57.209058,2.118854,58.168,0.097421,1.666667,0.946660
4,2017,권희동,NC,141,554,472,135,94,20,2,...,0.828742,0.281409,0.368644,0.815341,70.902062,2.626002,81.110,0.171610,5.181818,0.792685
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2021,최승민,NC,48,34,31,7,6,1,0,...,0.508065,0.177016,0.129032,0.481481,0.780331,0.028901,1.684,0.032258,0.000000,6.490188
155,2021,정진기,NC,86,199,186,43,29,8,0,...,0.645079,0.216092,0.284946,0.581081,14.325090,0.530559,18.934,0.139785,6.000000,1.363005
156,2021,김기환,NC,62,149,140,29,17,7,2,...,0.600000,0.200000,0.371429,0.626087,7.860817,0.291141,13.720,0.142857,5.000000,1.663757
157,2021,박대온,NC,42,95,85,18,17,1,0,...,0.465288,0.164674,0.070588,0.343284,2.744219,0.101638,5.362,0.011765,NaN,2.412802
158,2021,이원재,NC,31,69,65,15,13,2,0,...,0.511538,0.177885,0.092308,0.392157,3.051035,0.113001,4.292,0.030769,0.000000,3.188632

### OW%
Offensive winning percentage. The theoretical winning percentage of a team comprising nine of the same players

In [35]:
OW% = (RC/27)^2 / ((RC/27)^2 + 리그(RC/27)^2)

SyntaxError: invalid syntax (<ipython-input-35-cd79a9101801>, line 1)

In [36]:
bat_19

,연도,선수명,팀명,경기,타석,타수,안타,단타,2루타,3루타,...,OPS,GPA,SECA,TA,RC,RC27,XR,ISO,PSN,wOBA
0,2017,나성범,NC,125,561,498,173,105,42,2,...,0.999667,0.332983,0.489960,1.082353,98.029807,3.630734,107.792,0.236948,19.902439,0.896113
1,2017,박민우,NC,106,452,388,141,109,25,4,...,0.912629,0.316353,0.335052,0.980469,78.411222,2.904119,78.182,0.108247,4.714286,0.898347
2,2017,스크럭스,NC,115,518,437,131,72,24,0,...,0.996510,0.329436,0.588101,1.085987,84.405164,3.126117,100.468,0.295195,7.179487,0.918430
3,2017,손시헌,NC,124,391,349,122,99,17,1,...,0.833235,0.285557,0.212034,0.780172,57.209058,2.118854,58.168,0.097421,1.666667,0.946660
4,2017,권희동,NC,141,554,472,135,94,20,2,...,0.828742,0.281409,0.368644,0.815341,70.902062,2.626002,81.110,0.171610,5.181818,0.792685
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2021,최승민,NC,48,34,31,7,6,1,0,...,0.508065,0.177016,0.129032,0.481481,0.780331,0.028901,1.684,0.032258,0.000000,6.490188
155,2021,정진기,NC,86,199,186,43,29,8,0,...,0.645079,0.216092,0.284946,0.581081,14.325090,0.530559,18.934,0.139785,6.000000,1.363005
156,2021,김기환,NC,62,149,140,29,17,7,2,...,0.600000,0.200000,0.371429,0.626087,7.860817,0.291141,13.720,0.142857,5.000000,1.663757
157,2021,박대온,NC,42,95,85,18,17,1,0,...,0.465288,0.164674,0.070588,0.343284,2.744219,0.101638,5.362,0.011765,NaN,2.412802
158,2021,이원재,NC,31,69,65,15,13,2,0,...,0.511538,0.177885,0.092308,0.392157,3.051035,0.113001,4.292,0.030769,0.000000,3.188632

In [46]:
## 리그 RC27
L_RC = sum(bat_19['RC27']) / len(bat_19['RC27'])
L_RC

nan

In [49]:
bat_19['RC27']

3.6307335872515556

In [38]:
RC
A: 안타 + 볼넷 - 도루실패 + 몸에맞는공 - 병살타
B: (1.125×단타) + (1.69 x 2루타) + (3.02×3루타) + (3.73×홈런) + .29×(BB-IBB+HBP) + .492×(SH+SF+SB) - (0.4×K)
C: 타수 + 볼넷 + 몸에맞는 공 + 희생번트 + 희생플라이
((2.4C + A)*(3C + B)) / 9C - 0.9C

In [50]:
## 리그 RC/27
L_RC_list = []
L_A = sum(HIT) + sum(BB) - sum(CS) + sum(HP) - sum(GD)
L_B = ((1.125 * sum(HIT1)) + (1.69 * sum(HIT2)) + (3.02 * sum(HIT3)) + (3.73 * sum(HR)) + 
     (0.29 * (sum(BB) - sum(IB) + sum(HP))) + (0.492 * (sum(SH) + sum(SF) + sum(SB))) - (0.4 * sum(KK)))
L_C = sum(AB) + sum(BB) + sum(HP) + sum(SH) + sum(SF)
L_RC = (((2.4 * C) + A) * ((3 * C) + B)) / (9 * C) - (0.9 * C)
L_RC/729

0.004185233087290698

In [51]:
## 리그 RC/27
A_A = sum(HIT)/len(HIT) + sum(BB)/len(HIT) - sum(CS)/len(HIT) + sum(HP)/len(HIT) - sum(GD)/len(HIT)
A_B = ((1.125 * (sum(HIT)/len(HIT) - sum(HIT2)/len(HIT) - sum(HIT3)/len(HIT) - sum(HR)/len(HIT))) + 
       (1.69 * (sum(HIT2)/len(HIT))) + (3.02 * (sum(HIT3)/len(HIT))) + (3.73 * (sum(HR)/len(HIT))) + 
       (0.29 * (sum(BB)/len(HIT) - sum(IB)/len(HIT) + sum(HP)/len(HIT))) +
       (0.492 * (sum(SH)/len(HIT) + sum(SF)/len(HIT) + sum(SB)/len(HIT))) - (0.4 * (sum(KK)/len(HIT))))
A_C = sum(PA)/len(HIT) + sum(BB)/len(HIT) + sum(HP)/len(HIT) + sum(SH)/len(HIT) + sum(SF)/len(HIT)
A_RC = ((2.4 * A_C + A_A) * (3 * A_C + A_B)) / (9 * A_C) - 0.9 * A_C
A_RC = A_RC/27
A_RC

0.657763549479718

In [52]:
OW_list = []
for z in bat_19['RC27'] :
    OW_list.append((z**2) / ((z**2) + (L_RC**2)))

In [53]:
bat_19['OW%'] = OW_list
bat_19

,연도,선수명,팀명,경기,타석,타수,안타,단타,2루타,3루타,...,SECA,TA,RC,RC27,XR,ISO,PSN,wOBA,OW%,BABIP
0,2017,나성범,NC,125,561,498,173,105,42,2,...,0.489960,1.082353,98.029807,3.630734,107.792,0.236948,19.902439,0.896113,0.586110,0.412742
1,2017,박민우,NC,106,452,388,141,109,25,4,...,0.335052,0.980469,78.411222,2.904119,78.182,0.108247,4.714286,0.898347,0.475345,0.408284
2,2017,스크럭스,NC,115,518,437,131,72,24,0,...,0.588101,1.085987,84.405164,3.126117,100.468,0.295195,7.179487,0.918430,0.512153,0.352941
3,2017,손시헌,NC,124,391,349,122,99,17,1,...,0.212034,0.780172,57.209058,2.118854,58.168,0.097421,1.666667,0.946660,0.325368,0.383607
4,2017,권희동,NC,141,554,472,135,94,20,2,...,0.368644,0.815341,70.902062,2.626002,81.110,0.171610,5.181818,0.792685,0.425549,0.313514
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2021,최승민,NC,48,34,31,7,6,1,0,...,0.129032,0.481481,0.780331,0.028901,1.684,0.032258,0.000000,6.490188,0.000090,0.291667
155,2021,정진기,NC,86,199,186,43,29,8,0,...,0.284946,0.581081,14.325090,0.530559,18.934,0.139785,6.000000,1.363005,0.029352,0.258741
156,2021,김기환,NC,62,149,140,29,17,7,2,...,0.371429,0.626087,7.860817,0.291141,13.720,0.142857,5.000000,1.663757,0.009024,0.282609
157,2021,박대온,NC,42,95,85,18,17,1,0,...,0.070588,0.343284,2.744219,0.101638,5.362,0.011765,NaN,2.412802,0.001108,0.272727
158,2021,이원재,NC,31,69,65,15,13,2,0,...,0.092308,0.392157,3.051035,0.113001,4.292,0.030769,0.000000,3.188632,0.001370,0.272727

### BABIP
인플레이 타구에 대한 타율

In [43]:
BABIP = (H – HR)/(AB – K – HR + SF)

SyntaxError: invalid character in identifier (<ipython-input-43-232b85e04f52>, line 1)

In [44]:
BABIP_list = []
for y in range(0, len(bat_19)) :
    BABIP_list.append((HIT[y] - HR[y]) / (AB[y] - KK[y] - HR[y] + SF[y]))
bat_19['BABIP'] = BABIP_list
bat_19

<ipython-input-44-ff576388da59>:3: RuntimeWarning: invalid value encountered in longlong_scalars
  BABIP_list.append((HIT[y] - HR[y]) / (AB[y] - KK[y] - HR[y] + SF[y]))

,연도,선수명,팀명,경기,타석,타수,안타,단타,2루타,3루타,...,SECA,TA,RC,RC27,XR,ISO,PSN,wOBA,OW%,BABIP
0,2017,나성범,NC,125,561,498,173,105,42,2,...,0.489960,1.082353,98.029807,3.630734,107.792,0.236948,19.902439,0.896113,NaN,0.412742
1,2017,박민우,NC,106,452,388,141,109,25,4,...,0.335052,0.980469,78.411222,2.904119,78.182,0.108247,4.714286,0.898347,NaN,0.408284
2,2017,스크럭스,NC,115,518,437,131,72,24,0,...,0.588101,1.085987,84.405164,3.126117,100.468,0.295195,7.179487,0.918430,NaN,0.352941
3,2017,손시헌,NC,124,391,349,122,99,17,1,...,0.212034,0.780172,57.209058,2.118854,58.168,0.097421,1.666667,0.946660,NaN,0.383607
4,2017,권희동,NC,141,554,472,135,94,20,2,...,0.368644,0.815341,70.902062,2.626002,81.110,0.171610,5.181818,0.792685,NaN,0.313514
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2021,최승민,NC,48,34,31,7,6,1,0,...,0.129032,0.481481,0.780331,0.028901,1.684,0.032258,0.000000,6.490188,NaN,0.291667
155,2021,정진기,NC,86,199,186,43,29,8,0,...,0.284946,0.581081,14.325090,0.530559,18.934,0.139785,6.000000,1.363005,NaN,0.258741
156,2021,김기환,NC,62,149,140,29,17,7,2,...,0.371429,0.626087,7.860817,0.291141,13.720,0.142857,5.000000,1.663757,NaN,0.282609
157,2021,박대온,NC,42,95,85,18,17,1,0,...,0.070588,0.343284,2.744219,0.101638,5.362,0.011765,NaN,2.412802,NaN,0.272727
158,2021,이원재,NC,31,69,65,15,13,2,0,...,0.092308,0.392157,3.051035,0.113001,4.292,0.030769,0.000000,3.188632,NaN,0.272727

In [54]:
os.chdir(r'C:\Users\jaij2\OneDrive\바탕 화면\커뮤니티\데이터\NC')
bat_19.to_csv('2017_2021_NC_타자_saber.csv', encoding = 'cp949', index = False)